## Будем считать, что циклы я писать умею, поэтому задания 1 и 2 будут сделаны на основе матричных операций


In [1]:
import numpy as np

### Задание 1

In [2]:
def decl_array(num_el):
    return np.arange(num_el-1, -1, -1)

In [3]:
print(decl_array(5))

[4 3 2 1 0]


### Задание 2

In [5]:
N = 100
A = np.mat(np.diag(decl_array(N)))
ones_vect = np.mat(np.ones((N,1)))
diag_sum = ones_vect.T * A * ones_vect
print(diag_sum)

[[4950.]]


### Задание 3
решаем СЛАУ вида A*x = y

In [6]:
from numpy import linalg
A = np.array( [ [4,2,1], [1,3,0], [0,5,4]])
y = np.array( [ 4, 12, -3])
answer = linalg.solve(A, y)

print(answer)
#Checking
print(np.mat(A)* np.mat(answer).T)

[ 0.46666667  3.84444444 -5.55555556]
[[ 4.]
 [12.]
 [-3.]]
